homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf # general
  - apktool # necessary for Android reverse engineering
  - bash-completion #general
  - dependency-check # general
  - dex2jar #Android
  - doxygen #general
  - gettext #general
  - gifsicle #general
  - git #general
  - go #general
  - gpg #general
  - httpie #general
  - ideviceinstaller #used by appmon general
  - libimobiledevice #used by appmon general
  - mcrypt #used by appmon
  - nmap #general
  - node #used by appmon
  - python2 #general
  - python #python 3
  - testssl #general
  - openssl #general
  - wget #general
  - cmake #for idb (iOS)
  - usbmuxd #for idb (iOS)
  - libimobiledevice #for idb (iOS)
  - qt@4 #for idb (iOS)


homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - cartr/qt4 #idbtool

homebrew_cask_appdir: /Applications
homebrew_cask_installed_apps:
  - android-studio # android
  - java
  - jd-gui #android
