homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf # general
  - apktool # necessary for Android reverse engineering
  - bash-completion #general
  - dependency-check # general
  - dex2jar #Android
  - git #general
  - gpg #general
  - python2 #general
  - python #python 3
  - openssl #general
  - wget #general


homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_installed_apps:
  - android-studio # android
  - java
  - jd-gui #android
