---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  vars_files:
   - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:

  - include_tasks: tasks/ansible-setup.yml

  - name: print out the hostname of target
    command: hostname

  - name: install pip, if necessary
    include: tasks/install-pip.yml

#android
  - name: install drozer, if necessary
    include: tasks/install-drozer.yml
#Android
  - name: install Nathan, if necessary
    include: tasks/install-nathan.yml
#Android
  - name: install super analyzer, if necessary
    include: tasks/install-super-analyzer.yml
#Android
  - name: install Qark, if necessary
    include: tasks/install-qark.yml
