---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: false

  vars_files:
   - default.config.yml
  vars:
     home_directory: "{{ lookup('env', 'HOME') }}"
     
  tasks:

  - name: install pip, if necessary
    include: tasks/install-pip.yml

  - name: install homebrew items
    include: tasks/install-homebrew-items.yml
#android
  - name: install drozer, if necessary
    include: tasks/install-drozer.yml
#Android
  - name: install Nathan, if necessary
    include: tasks/install-nathan.yml
#Android
  - name: install super analyzer, if necessary
    include: tasks/install-super-analyzer.yml
#Android
  - name: install Qark, if necessary
    include: tasks/install-qark.yml
