# file: install-idb.yml
# http://www.idbtool.com/installation/
# Steps to take:
#- brew install prefered modules
#- brew install additional modules
#- gem install idb

#homebrew_tap is still in preview mode, which is why we use a script for the INSECURE qt4
- name: check to see if idb is already installed
  command: "which idb"
  ignore_errors: true
  register: idb_is_installed
  changed_when: false

- block:

  - name: tap qt4 (insecure)
    command: "brew tap cartr/qt4"

  - name: pin tap qt4 (insecure)
    command: "brew tap-pin cartr/qt4"

  - name: install qt4 (insecure)
    command: "brew install cartr/qt4/qt@4"

  - homebrew:
      name: cmake,usbmuxd,libimobiledevice
      state: present

  - name: install idbtool
    gem:
      name: idb
      state: present

  when: idb_is_installed.rc != 0
