# file: install-classdump.yml
# Used to install Classdump : http://stevenygard.com/projects/class-dump/
# Steps to take:
# - copy classdump and deprotect to classdump folder
# HVG!!

- name: check to see if classdump is already installed
  command: "class-dump"
  ignore_errors: true
  register: classdump_is_installed
  changed_when: false

- block:

    # TODO: move this to role vars as soon as using roles
    - name: determine class-dump binary dir
      set_fact:
        classdump_install_path: "{{ binary_install_path }}/classdump"

    - name: ensure classdump directory is present
      file:
        path: "{{ binary_install_path }}"
        state: directory

    - name: copy class-dump files
      copy:
        src: resources/classdump
        dest: "{{ classdump_install_path }}"

    - name: symlink class-dump binary
      file:
        path: "{{ binary_install_path }}/class-dump"
        src: "{{ classdump_install_path }}/classdump/class-dump"
        state: link

    - name: make class-dump executable
      file:
        path: "{{ binary_install_path }}/class-dump"
        mode: a+x

  when: classdump_is_installed.rc != 0
