- name: check if java is installed
  command: brew cask list java
  register: java_check
  ignore_errors: true

- name: install java
  command: brew cask install java
  when: java_check.stdout > "0"
  
- homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - autoconf
    - git
    - go
    - gpg
    - python2
    - node
    - python
    - openssl
    - wget
