# file: install-idb.yml
# http://www.idbtool.com/installation/
# Steps to take:
#- install rvm
#- brew install prefered modules
#- brew install additional modules
#- gem install idb

- block:

    - name: install idbtool
      gem:
        name: idb

  when: idb_is_installed.rc != 0
