---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  vars_files:
   - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:

  - name: print out the hostname of target
    command: hostname

  - name: install pip, if necessary
    include: tasks/install-pip.yml

#ios
  - name: install classdump, if necessary
    include: tasks/install-classdump.yml
#ios
  - name: install itms, if necessary
    include: tasks/install-itms.yml
#ios
  - name: install idb, if necessary
    include: tasks/install-idb.yml
