# file: install-appmon.yml
# Used to install Appmon : https://github.com/dpnishant/appmon
# Steps to take:
#- Download and extract into new directory
#- pip install everything
#- install prerequisites for a non-jailbroken device: https://github.com/dpnishant/appmon/wiki/4.c-Setup-for-a-non-jailbroken-iOS-Device
#- install prerequisites for an android non-rooted device: https://github.com/dpnishant/appmon/wiki/5.b-Setup-on-Android-%5BNon-Rooted%5D
#- inform the user that he has to go to https://github.com/dpnishant/appmon/wiki to continue

- name: check to see if Appmon is already installed
  command: "python /Applications/appmon/appmon-master/appmon.py -h"
  ignore_errors: true
  register: appmon_is_installed
  changed_when: false


- block:

#appmon host:
  - name: create directory
    command: "mkdir /Applications/appmon"

  - name: Unzip appmon
    unarchive:
      src: https://github.com/dpnishant/appmon/archive/master.zip
      dest: /Applications/appmon/
      remote_src: yes

  #appmon non-jailbroken ios:
  - name: install ios-deploy
    command: "npm install -g ios-deploy"

  - name: install dependencies
    command: "cd /Applications/appmon/appmon-master/ipa_installer && sh build.sh"

  - name: Remind people of further installation
    debug:
      msg: "https://github.com/dpnishant/appmon/wiki/4.c-Setup-for-a-non-jailbroken-iOS-Device for more details for ios"

  #host install finalize:
  - name: pip install everything
    command: "pip install argparse frida flask termcolor dataset htmlentities"



  when: appmon_is_installed.rc != 0
