# file: install-mobsf.yml
# Used to install MobSF : https://github.com/MobSF/Mobile-Security-Framework-MobSF
# Steps to take:
#- get the docker version up and running
#- git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF
#- cd into it and install it
#- make the installed version available in path

- name: check to see if mobsf is already installed
  command: "cat /Applications/mobsf/Mobile-Security-Framework-MobSF-master/manage.py"
  ignore_errors: true
  register: mobsf_is_installed
  changed_when: false

- block:

  - name: Creates directory
    file: path=/Applications/mobsf state=directory

  - name: Get mobsf docker container
    command: "docker pull opensecurity/mobile-security-framework-mobsf"

  - name: Unzip Mobsf git
    unarchive:
      src: https://github.com/MobSF/Mobile-Security-Framework-MobSF/archive/master.zip
      dest: /Applications/mobsf/
      remote_src: yes

  - name: install MobSF
    shell: |
      cd /Applications/mobsf/Mobile-Security-Framework-MobSF-master
      pip3 install virtualenv
      virtualenv -p python3 venv
      source venv/bin/activate
      pip3 install -r requirements.txt

  when: mobsf_is_installed.rc != 0
