# file: install-super-analyzer.yml
# Used to install SUPER : https://github.com/SUPERAndroidAnalyzer/super
# Steps to take:
#- download super in zip file and extract it
#- make it executable

- name: check to see if SUPER is already installed
  command: "super --help"
  ignore_errors: true
  register: super_is_installed
  changed_when: false

- block:
  - name: determine super binary dir
    set_fact:
      super_install_path: "{{ binary_install_path }}/super_package"

  - name: ensure super directory is present
    file:
      path: "{{ super_install_path }}"
      state: directory

  - name: Unzip super downloadable
    unarchive:
      src: https://www.dropbox.com/s/cclfxmd0o4wnsg8/super.zip?dl=1
      dest: "{{ super_install_path }}"
      remote_src: yes

  - name: symlink qark script
    file:
      path: "{{ binary_install_path }}/super"
      src: "{{ super_install_path }}/super/super-analyzer"
      state: link
  - name: make it executable
    command: "chmod +x {{ binary_install_path }}/super"
  when: super_is_installed.rc != 0
