# file: install-nathan.yml
# Used to install Nathan : https://github.com/mseclab/nathan
# Steps to take:
#- git downlaod https://github.com/mseclab/nathan
#- cd into it and execute ./nathan.py init
#- make sure it is in path

- name: check to see if nathan is already installed
  command: "which nathan"
  ignore_errors: true
  register: nathan_is_installed
  changed_when: false

- block:

  - name: determine nathan binary dir
    set_fact:
      nathan_install_path: "{{ binary_install_path }}/nathan_package"

  - name: Creates directory
    file:
      path: "{{ nathan_install_path }}"
      state: directory

  - name: Unzip Nathan
    unarchive:
      src: https://github.com/mseclab/nathan/archive/master.zip
      dest: "{{ nathan_install_path }}"
      remote_src: yes

  - name: copy nathan script files
    copy:
      src: resources/nathan.sh
      dest: "{{ nathan_install_path }}/nathan-master"

  - name: Initialize Nathan
    command: "cd {{ nathan_install_path }}/nathan-master ; ./nathan.py init"

  - name: symlink Nathan
    file:
      path: "{{ binary_install_path }}/nathan"
      src: "{{ nathan_install_path }}/nathan-master/nathan.sh"
      state: link

  - name: make qark executable
    file:
      path: "{{ binary_install_path }}/nathan"
      mode: a+x
  when: nathan_is_installed.rc != 0
