homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - apktool
  - bash-completion
  - dependency-check
  - dex2jar
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - httpie
  - python2
  - python3
  - testssl
  - mcrypt
  - nmap
  - openssl
  - wget


homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_installed_apps:
  - android-studio
  - atom
  - burp-suite
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - java
  - jd-gui
  - licecap
  - owasp-zap
  - packer
  - sequel-pro
  - slack
  - vagrant
  - virtualbox

mas_installed_apps:
  - { id: 497799835, name: "Xcode (9.4.1)" }
