homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf # general
  - bash-completion #general
  - dependency-check # general
  - doxygen #general
  - git #general
  - go #general
  - gpg #general
  - httpie #general
  - ideviceinstaller #used by appmon general
  - libimobiledevice #used by appmon general
  - mcrypt #used by appmon
  - nmap #general
  - node #used by appmon
  - python2 #general
  - python #python 3
  - testssl #general
  - openssl #general
  - wget #general


homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_installed_apps:
  - atom
  - burp-suite
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - java
  - owasp-zap
  - packer
  - sequel-pro
  - slack
  - vagrant
  - virtualbox
