---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  vars_files:
   - default.config.yml

  tasks:

  - name: print out the hostname of target
    command: hostname

  - name: install pip, if necessary
    include: tasks/install-pip.yml

  - name: install homebrew items
    include: tasks/install-homebrew-items.yml

  - name: add another cask
    command: "brew tap homebrew/cask"

  - name: install brew cask items
    include: tasks/install_homebrew_cask_items.yml
    with_items:
      - chromedriver
      - docker
      - java
      - vagrant
      - virtualbox
#general
  - name: install frida tools, if necessary
    include: tasks/install-frida.yml
#general
  - name: install mobsf, if necessary
    include: tasks/install-mobsf.yml
#General
  - name: install appmon, if necessary
    include: tasks/install-appmon.yml
#general
  - name: install objection, if necessary
    include: tasks/install-objection.yml
